data:
  t_sheet_name: 'x'
  a1_sheet_name: 'y'
  date_format: '%Y-%m-%d %H:%M:%S'
  t_a1_freq_ratio: 3
  t_a2_freq_ratio: 1
  key_var: 'x_0'
  file_name: '0_Simu/simu_data'
  test_size: 0.2
  t_d_model: 6
  a1_d_model: 4